version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd frontend/webpage
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
  baseDirectory: frontend/webpage
  files:
    - '**/*'
  cache:
    paths:
      - frontend/webpage/node_modules/**/*
